%: MakefileTest.coq phony
	+make -f MakefileTest.coq $@

all: all_coq sfi_safety_properties.exe mp.exe

all_coq: MakefileTest.coq 
	+make -f MakefileTest.coq all
	rm -f /tmp/run*test.mli
	rm -f /tmp/tl_quickchick_test.mli

sfi_safety_properties.exe: all_coq
	ocamlopt -I /tmp -o sfi_safety_properties.exe /tmp/run_test.ml Tests/I2SFI/main.ml

mp.exe: all_coq
	echo "open Big_int;;" > /tmp/tl_quickchick_test_1.ml
	cat /tmp/tl_quickchick_test.ml >> /tmp/tl_quickchick_test_1.ml
	ocamlopt -I /tmp -o mp.exe /tmp/tl_quickchick_test_1.ml Tests/I2MP/main.ml

clean: MakefileTest.coq
	+make -f MakefileTest.coq clean
	rm -f MakefileTest.coq
	rm -f /tmp/run*test.* 
	rm -f /tmp/tl_quickchick_test.ml*
	rm -f sfi_safety_properties.exe
	rm -f mp.exe

MakefileTest.coq: _CoqTestProject MakefileTest
	coq_makefile -f _CoqTestProject | sed 's/$$(COQCHK) $$(COQCHKFLAGS) $$(COQLIBS)/$$(COQCHK) $$(COQCHKFLAGS) $$(subst -Q,-R,$$(COQLIBS))/' > MakefileTest.coq

_CoqTestProject: ;

MakefileTest: ;

phony: ;

.PHONY: all clean phony sfi_safety_properties.exe mp.exe
